export const unitsImages = {
    anti_air:"/assets/units/anti_air.png",
    artillery_battery:"/assets/units/artillery_battery.gif",
    artillery_tank:"/assets/units/artillery_tank.png",
    artillery_truck:"/assets/units/artillery_truck.png",
    beast_rider:"/assets/units/beast_rider.gif",
    beast:"/assets/units/beast.png",
    fast_hover:"/assets/units/hover_copter.png",
    flying_beast:"",
    heavy_armoured_infantry:"/assets/units/heavy_armoured_infantry.webp",
    heavy_tank:"/assets/units/heavy_tank.png",
    heavy_weapons_infantry:"/assets/units/heavy_weapon_infantry.png",
    hover_transport:"/assets/units/transport_hover.png",
    infantry : '/assets/units/infantry.png',
    jet_infantry:"/assets/units/jet_infantry.webp",
    light_tank:"/assets/units/light_tank.png",
    light_infantry:"/assets/units/light_infantry.webp",
    monster:"",
    mid_tank:"/assets/units/mid_tank.png",
    rider:"/assets/units/rider.webp",
    transport_tank:"/assets/units/transport_tank.png",
    transport_armoured_tank:"/assets/units/light_tank.png",
    walker_wehicle:"/assets/units/walker_vehicle.png",
    warsuit:"/assets/units/war_suit.gif",
  }